KNOWLEDGE_FILES_RULES="Your filepath"
KNOWLEDGE_FILES_CONSTITUTION="Your filepath"
KNOWLEDGE_FILES_SERVER_INFO="Your filepath"
KNOWLEDGE_FILES_HOUSE_RULES = "Your filepath"
KNOWLEDGE_FILES_SENATE_RULES = "Your filepath"
KNOWLEDGE_FILES = {
    "rules": KNOWLEDGE_FILES_RULES,
    "constitution": KNOWLEDGE_FILES_CONSTITUTION,
    "server_information": KNOWLEDGE_FILES_SERVER_INFO,
    "house_rules": KNOWLEDGE_FILES_HOUSE_RULES,
    "senate_rules": KNOWLEDGE_FILES_SENATE_RULES
}
